var TREE_ITEMS = [

	['ROOT', null,
		
		['BRASIL', 0,
			['SAO PAULO', 0,
				['DEVICES', 0,
					['CS 2000 - A', 0,
						['DPPM 1'],
						['DPPM 2'],
						['ASM', 0],
					],
					['ALDE', 0,
						['ALDE 1'],
						['ALDE 2'],
					],
				],
				['ACCESS CONTROL', 0,
					['USERS', 0,
						['APERES'],
						['VICTORES'],
						['MBLIMA'],
						['ACEZAR', 0],
					],
					['PROFILES', 0,
						['PROFILE 1'],
						['PROFILE 2'],
					],
				],
				['POLICES', 0,
					['TRAFFIC', 0,
						['LIGHT 150'],
						['GOLD 1MB'],
					],
					['ACL +', 0,
						['WHITE LIST'],
						['BLACK LIST'],
						['ALDE'],
						['TRAFFIC']
					],
				],
			],
			
			['ALDE MASTER', 0,
				['ALERTS'],
				['ALERT USERS'],
			],
			['AUDITING', 0,
				['AUDIT MANAGER'],
				['QUERIES'],
			],
			['IN MON', 0,
				[''],
			],
		],
	],

];
