CREATE TABLE CSMUSERPROFILE (
    CONTEXT           INTEGER NOT NULL, /* FOREIGN KEY - CONTEXT
    PROID             INTEGER NOT NULL, /* PRIMARY KEY
    DESCRIPTION       VARCHAR (60) NOT NULL, 
    TYPE              INTEGER NOT NULL, /* 1 - Administrator, 2 - Operator, 3 - Guest, etc    
    SESSIONTIMEEXP    INTEGER, /* MINUTES
    FL_LOGINSIMULT    BOOLEAN,
    CREATEDDATETIME            VARCHAR (25),
    CREATEDBYUSERID            INTEGER

);

/* DEVICES DENIED PER USER 
CREATE TABLE CSMUSERDEVICE (
    USERID            INTEGER NOT NULL, /* PRIMARY KEY
    DEVICEID          INTEGER NOT NULL, FOREIGN KEY DEVICE
);



